id: Person
rows:
cols:
  idx:
    type: idx
  name:
    type: link
    title: some text to click
  title:
    type: text
  description:
    truncate: true
    value: AAA
  status:
    type: tag
    value: VAL
  order:
    value: ORDERs
