id: Person
rows:
cols:
  idx:
    type: idx
  name:
    type: link
    title: some text to click
  title:
    type: text
  desc:
    truncate: true
    value: AAA
  today:
    type: number
  tomorrow:
    type: number
  yesterday:
    type: number
  status:
    type: tag
    value: VAL
  order:
    type: number
    value: ORDERs
  deleted:
    type: bool
  delete_date:
    type: date
