id: Person
rows:
cols:
  idx:
    type: idx
  name:
    type: link
    #link: 'ctrl/edit/123'
    link: '{ctrl}/edit/{id}'
    #link: ['ctrl', '/edit', 'id_domain']
    title: some text to click
  title:
    type: text
  desc:
    truncate: true
  today:
    type: number
    total: sum
    unit: MB
  tomorrow:
    type: number
    total: avg
  yesterday:
    type: number
  status:
    type: tag
    tags:
      ok: green
      maybe: orange
      not: red
  order:
    type: number
  deleted:
    type: bool
  delete-date:
    type: date
    value: delete_date
  delete-date-format:
    type: date
    format: 'D, d-m-Y'
    value: delete_date
