id: Person
rows:
cols:
  idx:
    type: idx
  name:
    type: link
    title: some text to click
  title:
    type: text
  desc:
    truncate: true
    value: AAA
  today:
  tomorrow:
  yesterday:
  status:
    type: tag
    value: VAL
  order:
    value: ORDERs
  deleted:
  delete_date:
